export enum SPLIT_METHOD {
  EQUALLY = "EQUALLY",
  EXACT_AMOUNT = "EXACT_AMOUNT",
  PERCENTAGE = "PERCENTAGE",
  FULL_AMOUNT = "FULL_AMOUNT",
}

export enum USER_TRANSACTION_ACTION {
  LENT = "LENT",
  BORROWED = "BORROWED"
}
